<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('Contracts');
$coreDefs['dashlets'][0]['config']['link'] = 'contracts_activities_1_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'contracts_activities_1_notes';
$viewdefs['Contracts']['base']['view']['attachments'] = $coreDefs;
