<?php

$dictionary['Contract']['fields']['basic_commission_agent'] = array(
    'enforced' => '',
    'related_fields' =>
    array(
        0 => 'currency_id',
        1 => 'base_rate',
    ),
    'required' => false,
    'name' => 'basic_commission_agent',
    'label' => 'LBL_BASIC_COMMISSION_AGENT',
    'vname' => 'LBL_BASIC_COMMISSION_AGENT',
    'type' => 'currency',
    'massupdate' => false,
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => true,
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '26',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
    'dependency' => 'not(equal($provider_id_c,"bank_now_flex"))',
);
$dictionary['Contract']['fields']['basic_payout_date'] = array(
    'name' => 'basic_payout_date',
    'label' => 'LBL_BASIC_PAYOUT_DATE',
    'vname' => 'LBL_BASIC_PAYOUT_DATE',
    'type' => 'date',
    'module' => 'Contract',
    'default_value' => '',
    'help' => 'Date Field Help Text',
    'comment' => 'Date Field Comment',
    'mass_update' => false,
    'required' => false,
    'reportable' => true,
    'audited' => false,
    'duplicate_merge' => false,
    'importable' => true,
    'exportable' => true,
    'merge_filter' => 'selected',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'dependency' => 'not(equal($provider_id_c,"bank_now_flex"))',
);
$dictionary['Contract']['fields']['volume_commission_agent'] = array(
    'enforced' => '',
    'related_fields' =>
    array(
        0 => 'currency_id',
        1 => 'base_rate',
    ),
    'required' => false,
    'name' => 'volume_commission_agent',
    'label' => 'LBL_VOLUME_COMMISSION_AGENT',
    'vname' => 'LBL_VOLUME_COMMISSION_AGENT',
    'type' => 'currency',
    'massupdate' => false,
    'default' => NULL,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => true,
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'selected',
    'calculated' => false,
    'len' => '26',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
    'dependency' => 'not(equal($provider_id_c,"bank_now_flex"))',
);
$dictionary['Contract']['fields']['volume_payout_date'] = array(
    'name' => 'volume_payout_date',
    'label' => 'LBL_VOLUME_PAYOUT_DATE',
    'vname' => 'LBL_VOLUME_PAYOUT_DATE',
    'type' => 'date',
    'module' => 'Contract',
    'default_value' => '',
    'help' => 'Date Field Help Text',
    'comment' => 'Date Field Comment',
    'mass_update' => false,
    'required' => false,
    'reportable' => true,
    'audited' => false,
    'duplicate_merge' => false,
    'importable' => true,
    'exportable' => true,
    'merge_filter' => 'selected',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'dependency' => 'not(equal($provider_id_c,"bank_now_flex"))',
);
?>