<?php

$dictionary['Contact']['fields']['lead_source'] =
    array (
      'name' => 'lead_source',
      'vname' => 'LBL_LEAD_SOURCE',
      'type' => 'enum',
      'required' => false,
      'options' => 'lead_source_dom',
      'len' => '100',
      'comment' => 'How did the contact come about',
      'merge_filter' => 'enabled',
      'duplicate_merge' => 'enabled',  
    );

    $dictionary['Contact']['fields']['user_id_c'] = 
    array (
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'user_id_c',
      'vname' => 'LBL_CUSTOMER_CONTACT_USER_ID_USER_ID',
      'type' => 'id',
      'massupdate' => false,
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'required' => false,
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => false,
      'reportable' => false,
      'unified_search' => false,
      'merge_filter' => 'enabled',
      'calculated' => false,
      'len' => '36',
      'size' => '20',
    );

    $dictionary['Contact']['fields']['customer_contact_user_id_c'] =
    array (
      'labelValue' => 'Customer contact',
      'full_text_search' => 
      array (
        'boost' => '0',
        'enabled' => false,
      ),
      'dependency' => '',
      'required' => false,
      'source' => 'non-db',
      'name' => 'customer_contact_user_id_c',
      'vname' => 'LBL_CUSTOMER_CONTACT_USER_ID',
      'type' => 'relate',
      'massupdate' => false,
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'required' => false,
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'enabled',
      'calculated' => false,
      'len' => '255',
      'size' => '20',
      'id_name' => 'user_id_c',
      'ext2' => 'Users',
      'module' => 'Users',
      'rname' => 'name',
      'quicksearch' => 'enabled',
      'studio' => 'visible',
    );

     $dictionary['Contact']['fields']['lead_type_id_c'] =
    array (
      'labelValue' => 'Lead type',
      'dependency' => '',
      'visibility_grid' => '',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'lead_type_id_c',
      'vname' => 'LBL_LEAD_TYPE_ID',
      'type' => 'enum',
      'massupdate' => true,
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'enabled',
      'calculated' => false,
      'len' => 100,
      'size' => '255',
      'options' => 'dotb_lead_type_list',
    );