<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('Contacts');
$coreDefs['dashlets'][0]['config']['link'] = 'contacts_activities_1_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'contacts_activities_1_notes';
$viewdefs['Contacts']['base']['view']['attachments'] = $coreDefs;
