<?php
 // created: 2016-07-19 11:59:14
$dictionary['Task']['fields']['bank_c']=array (
      'name' => 'bank_c',
      'required' => false,
      'vname' => 'LBL_BANK',
      'type' => 'varchar',
      'source'=>'custom_fields',
      'massupdate' => true,
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => 255,
      'size' => '20',
    );
/*$dictionary['Task']['fields']['bank_c']=array (
      'name' => 'bank_c',
      'required' => false,
      'vname' => 'LBL_BANK',
      'type' => 'enum',
      'source'=>'custom_fields',
      'massupdate' => true,
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => 100,
      'size' => '20',
      'options' => 'dotb_credit_provider_list',
    );
 */
 ?>