<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','inactive-tasks');
$coreDefs['dashlets'][0]['filter']['module'] = array('Contacts');
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'contacts_activities_1_tasks';
$coreDefs['tabs'][0]['link'] = 'contacts_activities_1_tasks';
$coreDefs['tabs'][1]['link'] = 'contacts_activities_1_tasks';
$viewdefs['Contacts']['base']['view']['inactive-tasks'] = $coreDefs;
