<?php
    $dictionary['Opportunity']['fields']['contract_credit_amount']=
    array (
      'precision' => '2',
      'labelValue' => 'Credit Amount',
      'enforced' => '',
      'dependency' => 'not(equal($provider_id_c,"bank_now_flex"))',
      'related_fields' => 
      array (
        0 => 'currency_id',
        1 => 'base_rate',
      ),
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contract_credit_amount',
      'vname' => 'LBL_CONTRACT_CREDIT_AMOUNT',
      'type' => 'currency',
      'massupdate' => false,
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
    );
    
    $dictionary['Opportunity']['fields']['contract_credit_duration'] =
    array (
      'labelValue' => 'Credit Duration',
      'full_text_search' => 
      array (
        'boost' => '0',
        'enabled' => false,
      ),
      'enforced' => '',
      'dependency' => 'not(equal($provider_id_c,"bank_now_flex"))',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contract_credit_duration',
      'vname' => 'LBL_CONTRACT_CREDIT_DURATION',
      'type' => 'int',
      'massupdate' => false,
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
     
    );
    
    $dictionary['Opportunity']['fields']['contract_interest_rate']=array (
      'labelValue' => 'Interest Rate',
      'full_text_search' => 
      array (
        'boost' => '0',
        'enabled' => false,
      ),
      'enforced' => '',
      'dependency' => 'not(equal($provider_id_c,"bank_now_flex"))',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contract_interest_rate',
      'vname' => 'LBL_CONTRACT_INTEREST_RATE',
      'type' => 'decimal',
      'massupdate' => false,
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 2,
    );
    
    $dictionary['Opportunity']['fields']['contract_ppi']=array (
      'labelValue' => 'PPI',
      'enforced' => '',
      'dependency' => 'and(not(equal($provider_id_c,"rci")),not(equal($provider_id_c,"bank_now_flex")))',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'contract_ppi',
      'vname' => 'LBL_CONTRACT_PPI',
      'type' => 'bool',
      'massupdate' => false,
      'default' => false,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'enabled',
      'duplicate_merge_dom_value' => '1',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'calculated' => false,
      'len' => '255',
      'size' => '20',
    ); 
    $dictionary['Opportunity']['fields']['auto_assign_task']=array (
    'required' => false,
    'name' => 'auto_assign_task',
    'vname' => 'LBL_AUTO_ASSIGN_TASK',
    'type' => 'bool',
    'massupdate' => '0',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    );
 ?>